services:
  db:
    image: postgres:16-alpine
    container_name: mlops_db
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: mlops_api
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      MLFLOW_TRACKING_URI: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./reports:/app/reports
      - ./mlruns:/app/mlruns

  ingest:
    build: .
    profiles: ["tools"]
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    command: ["python", "-m", "src.data.make_dataset"]


  airflow-init:
    image: apache/airflow:3.2.2
    container_name: airflow_init
    depends_on:
      db:
        condition: service_healthy
    environment: &airflow-env
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/airflow
      AIRFLOW__CORE__EXECUTION_API_SERVER_URL: "http://airflow-apiserver:8080/execution/"
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
      AIRFLOW__API_AUTH__JWT_ISSUER: airflow
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    user: "${AIRFLOW_UID}:0"
    command:
      - db
      - migrate
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config

  airflow-apiserver:
    image: apache/airflow:3.2.2
    container_name: airflow_apiserver
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-env
    user: "${AIRFLOW_UID}:0"
    command: api-server
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config

  airflow-scheduler:
    image: apache/airflow:3.2.2
    container_name: airflow_scheduler
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-env
    user: "${AIRFLOW_UID}:0"
    command: scheduler
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config

  airflow-dag-processor:
    image: apache/airflow:3.2.2
    container_name: airflow_dag_processor
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment: *airflow-env
    user: "${AIRFLOW_UID}:0"
    command: dag-processor
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./config:/opt/airflow/config

volumes:
  pgdata:
