apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus_ds
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true

  - name: PostgreSQL
    uid: postgres_ds
    type: postgres
    access: proxy
    url: db:5432
    database: mlops
    user: romealnnr
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
